#!/bin/bash

## Vian Chen <imvianchen@stu.pku.edu.cn>

## This script emulates a micom binary.

path=$(dirname -- "$0")
interface=$(cat $path/interface 2>/dev/null)

if [[ ! "$interface" ]]; then
    interface='ioctl'
fi

function fatal {
    echo "micomd: $1"
    if [[ -z $2 ]]; then
        exit -1
    fi
    exit $2
}

function verbose {
    if [[ ! -z $DEBUG ]]; then
        echo "micomd (debug): $@"
    fi
}

function call_impl {
    case $interface in
        
        ioctl|mmio|procfs|netlink)
            verbose "Using interface: $interface"
            python3 $path/interfaces/pub.py "$interface" "$1"
            ;;

        *)
            fatal "Unknown interface: $interface"
            ;;

    esac
}

function exec_comm {
    case $2 in

        inject|inject-outgoing)
            comms=${@:3}
            call_impl "$comms"
            ;;

        *)
            fatal 'unrecognised sub-command.'
            ;;
    
    esac
}

# =============== Start of the main script ===============

case $1 in

    -c)
        exec_comm $@
        ;;
    
    *)
        fatal 'unrecognised command.'
        ;;

esac
