name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Go environment
      uses: actions/setup-go@v3.3.0
    - name: Build headers and the driver
      run: make header && make driver
    - name: Build watchdog client
      run: make watchdog-client